### ISSUE TITLE
\r\n in site_configuration breaks YAML parser

### ISSUE THREAD

**Issue by infabo** [IndyIndyIndy/yaml_browser#2]
```yaml
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /cn/\r\nSitemap: https://%env(SERVER_NAME)%/sitemap.xml"
```

throws exception here:

```YamlBrowser.init(configurationJson, matchesText);```
